/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package me.pocan.libraryx.ui;

import java.awt.geom.RoundRectangle2D;
import java.sql.Connection;
import javax.swing.JFrame;
import me.pocan.libraryx.modules.DatabaseModule;

/**
 *
 * @author ali
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 50, 50));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        left = new keeptoo.KGradientPanel();
        jLabel2 = new javax.swing.JLabel();
        Login_label = new javax.swing.JLabel();
        username_value = new javax.swing.JTextField();
        account_icon = new javax.swing.JLabel();
        password_value = new javax.swing.JPasswordField();
        password_icon = new javax.swing.JLabel();
        remember_me = new javax.swing.JCheckBox();
        forget_password_label = new javax.swing.JLabel();
        login_button = new com.k33ptoo.components.KButton();
        dont_have_account_label1 = new javax.swing.JLabel();
        dont_have_account_label2 = new javax.swing.JLabel();
        red_icon = new javax.swing.JLabel();
        orange_circle = new javax.swing.JLabel();
        green_circle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bgMouseMoved(evt);
            }
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bgMouseDragged(evt);
            }
        });

        left.setkEndColor(new java.awt.Color(255, 204, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/me/pocan/libraryx/ui/images/books.png"))); // NOI18N

        javax.swing.GroupLayout leftLayout = new javax.swing.GroupLayout(left);
        left.setLayout(leftLayout);
        leftLayout.setHorizontalGroup(
            leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel2)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        leftLayout.setVerticalGroup(
            leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftLayout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(102, 102, 102))
        );

        Login_label.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Login_label.setForeground(new java.awt.Color(102, 102, 102));
        Login_label.setText("Login");

        username_value.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        username_value.setText("user name");
        username_value.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));

        account_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/me/pocan/libraryx/ui/images/account.png"))); // NOI18N

        password_value.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        password_value.setText("********************");
        password_value.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));

        password_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/me/pocan/libraryx/ui/images/password.png"))); // NOI18N

        remember_me.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        remember_me.setForeground(new java.awt.Color(153, 153, 153));
        remember_me.setText("  Remember Me");

        forget_password_label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        forget_password_label.setForeground(new java.awt.Color(255, 0, 255));
        forget_password_label.setText("Forgot Password?");

        login_button.setText("Login");
        login_button.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 18)); // NOI18N
        login_button.setkBorderRadius(40);
        login_button.setkEndColor(new java.awt.Color(255, 204, 255));
        login_button.setkHoverEndColor(new java.awt.Color(255, 204, 255));
        login_button.setkHoverStartColor(new java.awt.Color(255, 204, 255));
        login_button.setkPressedColor(new java.awt.Color(255, 204, 255));
        login_button.setkStartColor(new java.awt.Color(255, 0, 255));
        login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_buttonActionPerformed(evt);
            }
        });

        dont_have_account_label1.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        dont_have_account_label1.setForeground(new java.awt.Color(102, 102, 102));
        dont_have_account_label1.setText("Don't have an account yet?");

        dont_have_account_label2.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 14)); // NOI18N
        dont_have_account_label2.setForeground(new java.awt.Color(255, 0, 255));
        dont_have_account_label2.setText("Sign up");

        red_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/me/pocan/libraryx/ui/images/red_circle.png"))); // NOI18N
        red_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                red_iconMouseClicked(evt);
            }
        });

        orange_circle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/me/pocan/libraryx/ui/images/orange_circle.png"))); // NOI18N

        green_circle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/me/pocan/libraryx/ui/images/green_circle.png"))); // NOI18N

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(left, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addComponent(remember_me)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                                        .addComponent(forget_password_label))
                                    .addComponent(password_value)
                                    .addComponent(username_value))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(account_icon)
                                    .addComponent(password_icon))
                                .addGap(32, 32, 32))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                                .addComponent(Login_label)
                                .addGap(159, 159, 159))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                                .addComponent(login_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(113, 113, 113))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                                .addComponent(red_icon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(orange_circle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(green_circle)
                                .addGap(18, 18, 18))))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(dont_have_account_label1)
                        .addGap(44, 44, 44)
                        .addComponent(dont_have_account_label2)
                        .addGap(0, 86, Short.MAX_VALUE))))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(left, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(red_icon)
                    .addComponent(orange_circle)
                    .addComponent(green_circle))
                .addGap(32, 32, 32)
                .addComponent(Login_label)
                .addGap(44, 44, 44)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(username_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(account_icon))
                        .addGap(43, 43, 43)
                        .addComponent(password_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(password_icon))
                .addGap(38, 38, 38)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(remember_me)
                    .addComponent(forget_password_label))
                .addGap(44, 44, 44)
                .addComponent(login_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dont_have_account_label1)
                    .addComponent(dont_have_account_label2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bgMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_bgMouseDragged

    private void bgMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseMoved
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_bgMouseMoved

    private void red_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_red_iconMouseClicked
        System.exit(0);
    }//GEN-LAST:event_red_iconMouseClicked

    private void login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_buttonActionPerformed
        DatabaseModule database = new DatabaseModule("5.180.105.88", 3306);
        Connection con = database.connectDatabase("s4230_test", "u4230_d7sjpDwh8O", ".t6.J4RuEV@48Zto.ddQn9ib");
        if (database.loginCheck(username_value.getText(), String.valueOf(password_value.getPassword()), con)) {


            
        }

        

        
        

        

        
    }//GEN-LAST:event_login_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }
    private int xx,xy;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Login_label;
    private javax.swing.JLabel account_icon;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel dont_have_account_label1;
    private javax.swing.JLabel dont_have_account_label2;
    private javax.swing.JLabel forget_password_label;
    private javax.swing.JLabel green_circle;
    private javax.swing.JLabel jLabel2;
    private keeptoo.KGradientPanel left;
    private com.k33ptoo.components.KButton login_button;
    private javax.swing.JLabel orange_circle;
    private javax.swing.JLabel password_icon;
    private javax.swing.JPasswordField password_value;
    private javax.swing.JLabel red_icon;
    private javax.swing.JCheckBox remember_me;
    private javax.swing.JTextField username_value;
    // End of variables declaration//GEN-END:variables
}
